mode: multimodal
from_pretrained: null

optimizer:
  _target_: Adam
  lr: 0.0003

scheduler:
  _target_: null

model:
  _target_: multimodal_base
  freeze_backbone: True

trainer:
  device: null
  min_epochs: 0
  max_epochs: 50
  grad_accum_steps: 1
  check_val_every_n_epochs: 1
  log_every_n_steps: 1
  resume_from_checkpoint: null
  output_dir: ./output/

data:
  data_dir: ./data/
  data_type: multimodal
  fold: 0
  n_folds: 5
  count_type: all
  batch_size: 32
  shuffle: true
  num_workers: 4
  pin_memory: false
  drop_last: true
